TipddyUPVBundle_homepage:
    pattern:  /
    defaults: { _controller: TipddyUPVBundle:Inscripcion:index }
    requirements:
        _method:  GET
    
TipddyUPVBundle_inscripcion:
        resource: "@TipddyUPVBundle/Resources/config/routing/inscripcion.yml"
        prefix:   /inscripcion
